#!/bin/sh
#
# Start logging
#

PL01=/usr/bin/bt_init
PL02=/usr/bin/bt_done

case "$1" in
  start)
	echo -n "Starting $0 : begin "

    [ -f $PL01 ] && ( $PL01 & ) || echo " file <$PL01> don't exist."

	echo -n "Starting $0 : end "
	;;
  stop)
	echo -n "Stopping $0 : "

    [ -f $PL02 ] && ( $PL02 ) || echo " file <$PL02> don't exist."

	echo "OK"
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
